name: golangchi-lint
on:
  push:
    branches:
      - dev
    pull_request:

permissions:
  contents: read

jobs:
  golangchi:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: golangchi-lint
        uses: golangci/golangci-lint-action@v5
